// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRoom(arg1:string):Promise<void>;

export function IsConnectedToServer():Promise<boolean>;

export function JoinRoom(arg1:number):Promise<void>;

export function Login(arg1:string):Promise<void>;

export function MakeChoice(arg1:number):Promise<void>;
