// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRoom(arg1) {
  return window['go']['main']['App']['CreateRoom'](arg1);
}

export function IsConnectedToServer() {
  return window['go']['main']['App']['IsConnectedToServer']();
}

export function JoinRoom(arg1) {
  return window['go']['main']['App']['JoinRoom'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function MakeChoice(arg1) {
  return window['go']['main']['App']['MakeChoice'](arg1);
}
